---
- name: Update and upgrade apt packages
  hosts: all
  become: true
  tasks:
    - name: Update apt packages
      ansible.builtin.apt:
        update_cache: true
    - name: Upgrade apt packages
      ansible.builtin.apt:
        upgrade: dist
        autoremove: true
        autoclean: true

- name: Install python3 and pip3
  hosts: all
  become: true
  tasks:
    - name: Install python3
      ansible.builtin.apt:
        name: python3
        state: present
    - name: Install python3-pip
      ansible.builtin.apt:
        name: python3-pip
        state: present

- name: Manage network interfaces
  hosts: all
  become: true
  tasks:
    - name: Dump grep matching interfaces from ansible_interfaces
      ansible.builtin.set_fact:
        interfaces_list: "{{ ansible_interfaces | select('match', '^(enp)[0-9]+') | list
        }}"

    - name: Configure network interfaces
      ansible.builtin.template:
        src: ./files/interfaces.j2
        dest: /etc/network/interfaces
        owner: root
        group: root
        mode: '0644'
      notify:
        - Apply network configuration

  handlers:
    - name: Apply network configuration
      ansible.builtin.systemd_service:
        name: networking
        state: restarted
        enabled: true
