- name: Populate service facts
  service_facts:

- name: Stop service rpcbind, if not started
  ansible.builtin.service:
    name: rpcbind
    state: stopped
  when: "'rpcbind' in services"

- name: Stop service rpcbind.socket, if not started
  ansible.builtin.service:
    name: rpcbind.socket
    state: stopped
  when: "'rpcbind.socket' in services"