- name: Install packages
  package:
    name:
      - tmux
      - rsync
      - zsh
      - rsync
      - wget
      - jq
      - curl
      - unzip
      - htop
      - sshfs
      - apache2-utils
      - nfs-common
      - mc
      - git
      - apache2-utils
      - neovim
    state: present