name: Run Ansible Playbook
run-name: ${{ github.actor }} is applying an ansible playbook 🚀
on: [push, pull_request, workflow_dispatch]
jobs:
    prep:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v2
        - name: Run ansible-lint
          uses: ansible/ansible-lint@main # or version tag instead of 'main'
          with:
            args: ansible-playbook.yml

    - name: Run Ansible Playbook
      uses: ansible/ansible-lint@main # or version tag instead of 'main'
      with:
          args: ansible-playbook.yml
      uses: ansible/ansible-lint@main # or version tag instead of 'main'
      with:
          args: ansible-playbook.yml
      uses: ansible/ansible-lint@main # or version tag instead of 'main'
      with:
          args: ansible-playbook.yml
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USERNAME }}
        key: ${{ secrets.REMOTE_SSH_KEY }}
        script: ansible-playbook ansible-playbook.yml